### ISSUE TITLE
Allow raw cell output to be rendered 

### ISSUE THREAD

**Issue by amichuda** [executablebooks/MyST-NB#295] opened 2021-01-21 01:39 UTC
When printing to console, it would be useful to have that output understood as just raw text, so that whatever is transforming can process and render it. For example, if you were converting to latex later, you could do something like this:

````
```{code-cell}
---
tags: [raw-cell]
---

print("""
\begin{center}
\begin{tabular}{ c c c }
 cell1 & cell2 & cell3 \\ 
 cell4 & cell5 & cell6 \\  
 cell7 & cell8 & cell9    
\end{tabular}
\end{center}
    """)
```
````

and have that printing to the console show up as a table in your latex output. This is something that's currently implemented in `pandoc` and `Rmarkdown` as well.

Would that be possible?

**Comment by amichuda** [comment] 2021-01-21 08:48
Following up on this, can glue do something like this? If I save the latex string to a glue variable, will I be able to render the latex in the document?

**Comment by chrisjsewell** [comment] 2021-01-22 08:52
heya I think this is a duplicate of #117?
I think it should be quite possible, I'm just updating myst-nb at present so I'll take this into account (it will be a few weeks away though probbly)

**Comment by choldgraf** [comment] 2021-01-23 23:25
I'm gonna close this because I _think_ that it is a dupe of #117, but I am not positive so @amichuda please re-open if we are wrong!

**Closed by choldgraf** 2021-01-23 23:25 UTC
Labels: enhancement
