### ISSUE TITLE
Copy local files/attachments to html build directory

### ISSUE THREAD

**Issue by ajz34** [executablebooks/MyST-NB#232] opened 2020-08-16 09:07 UTC
Hi devs!

**Is your feature request related to a problem? Please describe.**

I have a directory like
```
source
- note.ipynb
- input.dat
build/html
- note.html
```
but there's no `build/html/input.dat`.

I want to add a link in `note.ipynb` like
```markdown
This is the [input file](input.dat), please use that file to give correct output.
```
but this is parsed as an invalid link currently.

**Describe the solution you'd like**

Maybe enabling copying all (valid, excluding .ipynb_checkpoints, \_\_py_cache\_\_, etc., or specified by user) local files to `build/html` folder may could resolve this feature.

**Describe alternatives you've considered**

I'm also [nbsphinx](https://github.com/spatialaudio/nbsphinx/) user. That package seems supporting this feature.

I guess something like function [html_collect_pages](https://github.com/spatialaudio/nbsphinx/blob/2a58e97955a4df4c07f64bedaba013c6ee2484b6/src/nbsphinx.py#L1898) in nbsphinx is its solution. But I actually don't know how to debug sphinx extensions, so just a guess.

**Comment by choldgraf** [comment] 2020-08-17 01:02
I think this one is a close-to-duplicate of https://github.com/executablebooks/jupyter-book/issues/790

the short answer is that for now you can use the `download` role to mark a file as downloadable (and it will then be copied over when your book is built). Perhaps we can iterate on another solution in the other issue?

I'll close this but if you think it is not a duplicate, feel free to re-open!

**Closed by choldgraf** 2020-08-17 01:02 UTC
Labels: enhancement

**Comment by ajz34** [comment] 2020-08-17 05:32
Hi Chris!

Thanks for comment! This solution could quite mitigate the workflow of mine!
I was finding in MyST-NB and sphinx-book-theme, but not jupyter-book 😅 It is actually quite close-to-duplicate that issue.
Disscussion there is quite plenty 😄

I wonder whether this feature is going to be described in https://myst-parser.readthedocs.io/en/latest/using/syntax.html 😂
