### ISSUE TITLE
Way to render markdown table in cell output?

### ISSUE THREAD

**Issue by rossbar** [executablebooks/MyST-NB#200] opened 2020-06-16 04:40 UTC
**Is your feature request related to a problem? Please describe.**
I have a function that returns a markdown-formatted table as a Python string, e.g. 

```python
def create_table():
    return "|a|b|\n|:--:|:--:|\n|1|2|"
```

In an Jupyter notebook with an interactive kernel, this could be rendered with `display.Markdown`:

```python
my_table = create_table()
from IPython.display import Markdown
Markdown(my_table)
```

With `myst_nb`, the above produces the following output in the html:

```
<IPython.core.display.Markdown object>
```

I considered `glue` as an alternative, but the `glue` directive results in a textbox with the raw Python string.

**Describe the solution you'd like**
There might already be a straightforward way to do this - if so, please disregard (though maybe consider adding it to the documentation).

Ideally there would be some way to convert cell output into a richer/rendered form, similar to what `IPython.display` does when there is an interactive kernel.

**Describe alternatives you've considered**
Using a markdown parser (e.g. `commonmark`) to parse to html, then programatically add a new cell with the html as input (instead of cell output).

**Comment by chrisjsewell** [comment] 2020-06-16 04:44
Hey @rossbar, this is actually a duplicate of #31, which we are also discussing in #198 😄

**Comment by rossbar** [comment] 2020-06-16 04:47
Of course it is - sorry for all the duplicates!

**Closed** 2020-06-16 04:46 UTC
Labels: duplicate, enhancement
