### ISSUE TITLE
Images embedded in .ipynb files creating error

### ISSUE THREAD

**Issue by mukulpareek** [executablebooks/MyST-NB#413] opened 2022-05-04 01:32 UTC
Jupyter notebooks allow copy/pasting images from the clipboard into markdown cells.  These images (eg, using Snippy on Windows) are embedded in the .ipynb file as base64 images.  Jupyterbooks errors out on such cells, and the build fails.

Does anyone know a workaround to this?

For example, the error would be `[91mC:\Users\user\Google Drive\jupyter\mynewbook\03._Visualization_Basics.ipynb:10009: WARNING: image file not readable: attachment:5e81266f-de1a-4646-a45b-ce7efb2b90a8.png←[39;49;00m`

That is because it probably is not able to extract 5e81266f-de1a-4646-a45b-ce7efb2b90a8.png from the .ipynb file, but is able to get the images for graphics generated by the code in the cells.

**Comment by choldgraf** [comment] 2022-05-04 12:35
I think that this one belongs in the MyST-NB repository rather than `meta/`, though not positive. I'm not sure whether we support embedded base64 images or not, though should confirm this one way or another.

**Comment by kolibril13** [comment] 2023-04-13 18:06
I experienced the same issue and wrote a detailed bug report https://github.com/executablebooks/MyST-NB/issues/492 here. I just discovered this issue ticket after creating the new one, so one can be closed as a duplicate.

**Comment by bsipocz** [comment] 2024-09-19 22:29
I'm closing this as a duplicate of #492, even though that one was opened later, it includes useful details for fixing this bug.

**Closed by bsipocz** 2024-09-19 22:29 UTC
